name: "dnsx Action"
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: 💥 dnsx - DNS Resolver
        uses: projectdiscovery/dnsx-action@main
        with:
          json: true
          list: domains.txt
          resolver: resolvers.txt
          output: dns.txt
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: 💥 dnsx - DNS Resolver
          path: dns.txt
          
