name: "dnsx Action"
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: 💥 dnsx - DNS Resolver
        uses: projectdiscovery/dnsx-action@main
        with:
          list: domains.txt
          resolver: resolvers.txt

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dnsx.txt
          path: dnsx.txt
